from pygame.version import ver

# Pygame Info
PYGAME_VERSION = ver

# Screen Settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_FILL_COL = "black"
SCREEN_FPS = 60

LINE_WIDTH = 2

# Asteroid Settings
ASTEROID_COL = "white"
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player Settings
PLAYER_COL = "white"
PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3


# Bullet Settings
SHOT_COLOR = "red"
SHOT_RADIUS = 5


# Messages
GAME_OVER_MESSAGE = "Game over!"
